import type { Extractor } from "./interfaces/extractor.js";
import type { Formatter } from "./interfaces/formatter.js";
import type { TranslationProvider } from "./interfaces/translator.js";
import type { HookAdapter } from "./interfaces/hook-adapter.js";

/** Result of extracting a single string from source code. */
export interface ExtractionResult {
  /** The original string literal */
  text: string;
  /** Where it was found in source */
  location: SourceLocation;
  /** Context hint for translators (e.g., "button label", "page title") */
  context?: string;
  /** Generated i18n key (e.g., "hero.hello_world") */
  key: string;
}

export interface SourceLocation {
  file: string;
  line: number;
  column: number;
}

/** Result of replacing strings in a source file. */
export interface ReplaceResult {
  /** Modified source code */
  output: string;
  /** Whether the file was changed */
  modified: boolean;
}

/** A batch of translations for a single target language. */
export interface TranslationResult {
  language: string;
  translations: Record<string, string>;
}

/** Hook configuration generated by a HookAdapter. */
export interface HookConfig {
  /** Path to write the hook config file */
  path: string;
  /** Content of the hook config file */
  content: string;
}

/** Resolved linguo configuration. */
export interface LinguoConfig {
  sourceLanguage: string;
  targetLanguages: string[];
  include: string[];
  exclude?: string[];
  outDir: string;
  extractors: Extractor[];
  formatters: Formatter[];
  translators?: TranslationProvider[];
  hookAdapters?: HookAdapter[];
}
